### ISSUE TITLE
Timeout when finding tradeup

### ISSUE THREAD

**Issue by SunfxDEV** [StiliyanKushev/csgo-tradeup-cli#13]
When the algorithm finds a profitable tradeup it usually generates a tradespylink, but sometimes im getting
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.evaluate: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('.searched_skins_container_enabled>a') to be visible
============================================================
```

Im guessing that means tradeupspy isnt responding, i would appreciate either a message that exactly tells me what happens here instead of 
`name: 'Error'`
or a option to extend the wait until tradeupspy responds

**Comment by StiliyanKushev** [comment]
Will take a look in the upcoming days.

**Comment by NORXONDOR** [comment]
What are you running to generate the skin database?

**Comment by TomiLikesToCode** [comment]
What operating system is this code supposed to run on?

**Comment by StiliyanKushev** [comment]
Should automatically extend the waiting and not crash now.
