### ISSUE TITLE
--eval Throwing weird errors

### ISSUE THREAD

**Issue by SunfxDEV** [StiliyanKushev/csgo-tradeup-cli#14]
Upon trying **--smart** and **--eval** with a path such as "./result.json" (which is in the help as an example) im getting the error:
![image](https://user-images.githubusercontent.com/95370363/227793638-43bcf55c-3c94-414f-9fa3-0d2185907b91.png)
![image](https://user-images.githubusercontent.com/95370363/227793659-92c533cb-8ebf-4959-a583-05711c0820af.png)

**Comment by StiliyanKushev** [comment]
In your example, the JSON file "./result.json" does not exist. --eval accepts an input file, not an output path.
