### ISSUE TITLE
The Anubis collection error 

### ISSUE THREAD

**Issue by TomiLikesToCode** [StiliyanKushev/csgo-tradeup-cli#17]
The Anubis collection error is caused by skipping all skins because they are all souvenirs in Anubis collection resulting in utils/rarity.js getting no info and making error undefined

**Comment by ellysus** [comment]
see [#16](https://github.com/StiliyanKushev/csgo-tradeup-cli/issues/16

**Comment by TomiLikesToCode** [comment]
> see #16 

Nice

**Comment by ellysus** [comment]
@TomiLikesToCode were you able to run the project properly after this fix? I'm getting an imports issue (#18), do you mind letting me know how you managed to fix it or what your NodeJS version is?

**Comment by TomiLikesToCode** [comment]
> @TomiLikesToCode were you able to run the project properly after this fix? I'm getting an imports issue (#18), do you mind letting me know how you managed to fix it or what your NodeJS version is?

I will try it tomorrow and let you know
